info:
  artifactId: '${project.name}'
  version: '${project.version}'

server:
  port: 9093

---
spring:
  cloud:
    gateway:
      routes:
        - id: first-route
          uri: http://localhost:9094/
          predicates:
            - Path=/cash-back/2
          filters:
            - AddRequestHeader=Gabriel,Felix
            - AddRequestParameter=red, blue